x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  event-indexer-arb:
    #    image: us-docker.pkg.dev/mxczkevm/images/event-indexer:moonchain-dev
    build:
      context: ../
      args:
        PACKAGE: eventindexer
    restart: unless-stopped
    depends_on:
      - mysql
    pull_policy: always
    env_file:
      - event-indexer/.l1.arb.env
    environment:
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      RPC_URL: ${L1_RPC_URL}
    volumes:
      - ./script:/script
    tty: true
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-l1-indexer.sh"
    <<: *logging
  event-indexer-api:
    #    image: us-docker.pkg.dev/mxczkevm/images/event-indexer:moonchain-dev
    build:
      context: ../
      args:
        PACKAGE: eventindexer
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - mysql
    env_file:
      - event-indexer/.l1.arb.env
    environment:
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      RPC_URL: ${L2_RPC_URL}
    volumes:
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-api.sh"
    <<: *logging
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: eventindexer
    ports:
      - 33069:3306
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    <<: *logging
